server.port=8081
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:postgresql://localhost:5432/consumer_a
spring.datasource.username=consumer_a_app
spring.datasource.password=consumer_a_pw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=false

# Pulsar
spring.pulsar.client.service-url=pulsar://localhost:6650

# App
app.pulsar.topic=persistent://public/default/stations.changelog
app.pulsar.subscription=consumer-a
app.pulsar.iteration=1
