spring.datasource.url=jdbc:postgresql://localhost:5432/consumer_b
spring.datasource.username=consumer_b_app
spring.datasource.password=consumer_b_pw
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8083

app.pulsar.subscription=consumer-b
app.pulsar.iteration=2