server.port=8082
spring.thymeleaf.cache=false

# DB (producer/SoT)
spring.datasource.url=jdbc:postgresql://localhost:5432/station_sot
spring.datasource.username=producer_app
spring.datasource.password=producer_pw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=false

# Pulsar
spring.pulsar.client.service-url=pulsar://localhost:6650
app.pulsar.topic=persistent://public/default/stations.changelog
